const Map<String, String> enTranslations = {
  // --- login ---
      'login': 'Login',
      'loginTitle': 'Inventory',
      'logout': 'Logout',
      'username': 'Username',
      'phone': 'Phone',
      'password': 'Password',
      'rememberMe': 'Remember me',
      'home': 'Home',
      'PickupLocation': 'Pickup Location',
      'DropoffLocation': 'Dropoff Location',
      'BookNow': 'Book Now',
      'register': 'Register',
      'notification': 'Notification',

      // --- Common / UI ---
      'add': 'Add',
      'add_user': 'Add User',
      'cancel': 'Cancel',
      'close': 'Close',
      'confirm': 'Confirm',
      'delete': 'Delete',
      'edit': 'Edit',
      'error': 'Error',
      'language': 'Language',
      'loading': 'Loading...',
      'no_data': 'No data available',
      'no_users_found': 'No users found.',
      'save': 'Save',
      'Save': 'Save',
      'Back': 'Back',
      'back': 'Back',
      'search': 'Search',
      'submit': 'Submit',
      'update': 'Update',

      // --- Product Management ---
      'products': 'Products',
      'product': 'Product',
      'add_product': 'Add Product',
      'edit_product': 'Edit Product',
      'delete_product': 'Delete Product',
      'update_product': 'Update Product',
      'no_products_found': 'No products found',
      'product_name': 'Product Name',
      'product_code': 'Product Code',
      'sku': 'SKU',
      'description': 'Description',
      'category': 'Category',
      'brand': 'Brand',
      'unit_price': 'Unit Price',
      'cost_price': 'Cost Price',
      'stock_quantity': 'Stock Quantity',
      'minimum_stock': 'Minimum Stock',
      'unit_of_measure': 'Unit of Measure',
      'weight': 'Weight',
      'dimensions': 'Dimensions',
      'barcode': 'Barcode',
      'supplier_id': 'Supplier ID',
      'notes': 'Notes',
      'field_required': 'This field is required',
      'product_updated_successfully': 'Product updated successfully',
      'product_discontinued_successfully': 'Product discontinued successfully',
      'delete_product_confirmation':
          'Are you sure you want to discontinue this product?',
      'confirm_delete': 'Confirm Delete',
      'low_stock': 'Low Stock',
      'discontinued': 'Discontinued',
      'inactive': 'Inactive',
      'all': 'All',
      'stock': 'Stock',
      'search_hint': 'Search by name, code, SKU, or brand...',
      'check_low_stock': 'Check Low Stock',
      'no_search_results': 'No products match your search criteria',
      'low_stock_alert': '{count} products are low in stock!',
      'products_low_stock': 'products are low in stock!',
      'adequate_stock_message': 'All products have adequate stock levels',

      // --- Navigation / Pages ---
      'assignment': 'Assignment',
      'car': 'Car Control',
      'car_credit': 'Car Credit Status',
      'history': 'History',

      'locations': 'Booking Locations',
      'reservation': 'Reservation',
      'setting': 'Settings',
      'user': 'User',
      'view_car': 'View Car',
      'welcome_home': 'Welcome Home!',

      // --- register---
      'bank': 'Bank',
      'province': 'Province',
      'district': 'District',
      'village': 'Village',
      'AccountNumber': 'Account Number',
      'AccountName': 'Account Name',
      'email': 'Email',
      'DocumentID': 'Document ID',
      'name': 'FullName',
      'photo': 'Photo',
      'photoID': 'Photo ID',
      'RegisterPage': 'Register New User',
      'UserInfoPage': 'User Info',
      'UpdateUserInfo': 'Update User',
      'saveChanges': 'Save',
      'updateSuccess': 'Update Success',
      'pictureId': 'Car Profile',
      'picture1': 'Yello book',
      'picture2': 'Driver license',
      'picture3': 'Insurance',

      'picture_Id': 'Car Profile',
      'CarAddPage': 'Car Register',

      'model': 'Car model',
      'license_plate': 'Car license_plate',
      'car_type': 'Car Type',
      'Carprovince': 'Car Province',
      'Suggested': 'Suggested Fare Price (LAK)',
      'FareOffer': 'Your Fare Offer (LAK)',

      // -------booking ------
      "Booking": "Booking",
      "Phone": "Phone",
      "Date": "Date",
      "Time": "Time",
      "Status": "Status",
      "LicensePlate": "License Plate",
      "CarProvince": "Car Province",
      "CarType": "Car Type",
      "CarTypeLA": "Car Type (LA)",
      "Driver": "Driver",
      "Pickup": "Pickup",
      "Dropoff": "Dropoff",
      // "Suggested": "Suggested Price",
      "Payment": "Payment Price",
      "RateThisService": "Rate this service:",
      "SubmitReview": "Submit Review",
      "OpenInMap": "Open in Map",
      "CouldNotOpenMap": "Could not open Google Maps",

      // driver
      'driver_dashboard': 'Dashboard',
      'welcome': 'Welcome',
      'status': 'Status',
      'go_online': 'Go Online',
      'go_offline': 'Go Offline',
      'my_bookings': 'My Bookings',
      'pickup_time': 'Pickup at 10:30 AM',
      'online': 'Online',
      'offline': 'Offline',
      'my_car': 'My Car',
      "no_cars_found": "no cars found",
      "no_image_selected": "no image selected",

      //----------drver confrim
      "booking_confirmation": "booking confirmation",
      "pickup_location": "pickup",
      "dropoff_location": "dropoff",
      "price": "Price",
      "suggested_price": "Suggested",
      "distance": "Distance",
      "confirm_booking": "Confirm Booking",
      "no_bookings_found": "No Found",
      "network_error": "network error",

      'no_bookings': 'No bookings found',
      'offline_message': 'You are offline — no bookings',
      'message': 'Message',

      'booking_confirmed': 'Booking Confirmed',
      'booking_accepted': 'Your booking has been accepted by the driver.',
      'driver_arrived': 'Driver Arrived',
      'driver_at_pickup': 'Your driver has arrived at the pickup location.',
      'carInfoPage': 'Car Information',

      'car_province_id': 'Province',
      'car_type_id': 'Car Type',

      'car_added_successfully': 'Car added successfully',
      'select_province': 'Please select a province',
      'select_car_type': 'Please select a car type',
      'enter_brand': 'Please enter brand',
      'enter_model': 'Please enter model',
      'enter_license_plate': 'Please enter a valid license plate',
      'addCar': 'Add Car',
      "pickup": "Pickup",
      "dropoff": "Dropoff",
      "booking_details": "Booking Details",
      "booking_id": "Booking ID",
      "passenger": "Passenger",
      "driver": "Driver",
      "add_car_first": "Add Car First",
      "no_car_assigned": "No Car Assigned",
      "add_car": "Add Car First",
      "no_data_found": "No Data Found",
      "PassengerName": "Passenger Name",
      'PasswordTooEasy': 'Password Too Easy',
      'PasswordMedium': 'Password Medium',
      'PasswordStrong': 'Password Strong',
      'PasswordMin6Chars': 'Password Min 6 Chars',

      "SelfiePhoto": "🧍 Selfie Photo",
      "IDCardPhoto": "🪪 ID Card Photo",
      "TakeSelfie": "Take a clear photo of yourself",
      "UploadID": "Upload your National ID or Passport",
      "message_detail": "Message",

      "VerifyPhone": "Verify Phone",
      // "phone": "Phone Number",
      "GetOtp": "Get OTP",
      "YourOtp": "Your OTP",
      "EnterPhoneRequired": "Phone number is required",
      "FailedToGetOtp": "Failed to get OTP",
      "ServerError": "Server error",
      "RequestFailed": "Request failed",
      'EnterYourPhoneToGetOtp': 'Enter Your Phone To Get OTP',
      'confirmPassword': 'confirm Password',
      // 'no_bookings_found': 'no bookings found',
      'SelectCarType': 'Select Car Type',
      'YourPrice': 'Your Price',
      'no_messages_found': 'no messages found',
      'InvalidPhoneFormat': 'Invalid Phone \n 20 XXXX XXXX ',

      // "setting": "Setting",
      'ConfirmOtp': 'Confirm OTP',
      'PhoneLabel': 'Phone',
      'OtpSentLabel': 'OTP sent',
      'EnterOtp': 'Enter OTP',
      'VerifyOtp': 'Verify OTP',
      'EnterOtpRequired': 'Please enter the OTP',
      'InvalidOtp': 'Invalid OTP',
      'OtpVerifiedSuccess': '✅ OTP verified successfully!',
      "OtpDailyLimitReached":
          "You have reached the daily OTP limit (5). Please try again tomorrow.",
      'ConfirmPassword': 'ConfirmPassword',

      // "FailedToGetOtp": "Failed to get OTP. Please try again."
      'PasswordsDoNotMatch': 'Passwords Do Not Match',
      'PleaseSelectSelfieAndID': 'Selfie',
      'PasswordsMatch': 'Passwords Matched',
      'Register': 'Register',

      'insurance_no': 'Insurance No',
      'enter_insurance_no': 'Enter Insurance No',
      'insurance_date': 'Exprice Date Insurance',
      'select_date': 'Select Exprice Date Insurance',
      'document_id': 'ID Card Number',
      'village_name': 'Village Name',
      'district_name': 'District Name',
      'province_name': 'Province Name',
      'booking_timeout_message': 'booking timeout',
      'booking_timeout': 'Timeout',
      'Ok': 'OK',

      // New keys needed for enhanced driver app
      'accepting_bookings': 'Accepting Bookings',
      'not_accepting_bookings': 'Not Accepting Bookings',
      'current_location': 'Current Location',
      'location_unavailable': 'Location Unavailable',
      'available_bookings': 'Available Bookings',
      'searching_bookings': 'Searching for bookings...',
      'showing_recent_bookings': 'Showing bookings from last 5 minutes only',
      'add_car_to_start':
          'Please add your vehicle information to start receiving bookings',
      'your_location': 'Your Location',
      'customer_name': 'Customer Name',
      'vehicle_type': 'Vehicle Type',
      'updating': 'Updating...',
      'start_trip': 'Start Trip',
      'complete_trip': 'Complete Trip',
      'call': 'Call',
      'navigate': 'Navigate',
      'navigate_pickup': 'Navigate to Pickup',
      'call_customer': 'Call Customer',
      'trip_details': 'Trip Details',

      'booking_time': 'Booking Time',
      'passenger_note': 'Passenger Note',
      'payment_method': 'Payment Method',
      'booking_cancelled': 'Booking Cancelled',
      'booking_cancelled_message':
          'This booking has been cancelled by the customer.',
      'confirming': 'Confirming...',
      'expired': 'Expired',
      'remaining': 'Remaining',
      'cancelled': 'Cancelled',
      'customer': 'Customer',

      'ForgetPassword': 'Forget Password',
      'EnterPhoneToResetPassword': 'Enter your phone number to reset password',
      'GetOtpForReset': 'Get OTP for Reset',
      'forget password': 'Forget Password',
      'VerifyOtpForReset': 'Verify OTP for Reset',
      'EnterOtpSentToPhone': 'Enter the OTP sent to your phone',
      'EnterCompleteOtp': 'Please enter complete 6-digit OTP',
      'ResendOtp': 'Resend OTP',
      'OtpVerificationFailed': 'OTP verification failed',
      'OtpSentAgain': 'OTP sent again to your phone',
      'FailedToResendOtp': 'Failed to resend OTP',

      'ConfirmYourPassword': 'Please confirm your password',
      'WeakPassword': 'Weak Password',
      'FairPassword': 'Fair Password',
      'GoodPassword': 'Good Password',
      'StrongPassword': 'Strong Password',

      // ForgetPasswordPage translations
      'ResetPassword': 'Reset Password',
      'CreateNewPassword': 'Create New Password',
      'NewPassword': 'New Password',
      'EnterNewPassword': 'Please enter new password',
      'PasswordTooShort': 'Password must be at least 6 characters',
      'UpdatePassword': 'Update Password',
      'PasswordResetSuccess':
          'Password reset successfully! Redirecting to login...',
      'PasswordResetFailed': 'Failed to reset password',

      // BookingListPage translations
      'booking_history': 'Booking History',
      'grouped_by_status': 'Grouped by status',
      'total_bookings': 'Total Bookings',
      'completed': 'Completed',
      'filtered_by': 'Filtered by',
      'no_bookings_filtered': 'No bookings found',
      'no_bookings_for_status': 'No bookings with status',
      'no_bookings_desc': 'Your completed trips will appear here',
      'clear_filter': 'Clear Filter',
      'refresh': 'Refresh',
      'active': 'Active',
      'total': 'Total',
      'your_trip_history': 'Your trip history and earnings',
      'payment_price': 'Payment Price',
      'refresh_profile': 'Refresh Profile',
      // ProfilePage
      'account_no': 'Account Number',
      'account_name': 'Account Name',
      'bio': 'Bio',
      'driver_status': 'Driver Status',
      // MessagePage
      'notifications': 'Notifications',
      'unread': 'unread',
      'mark_all_read': 'Mark all as read',
      'no_messages': 'No Messages',
      'no_messages_desc': 'You\'ll see your notifications and updates here',
      'payment_completed': 'Payment Completed',
      'payment_success': 'Your payment has been processed successfully',
      'rate_trip': 'Rate Your Trip',
      'please_rate': 'Please rate your recent trip experience',
      'special_offer': 'Special Offer',
      'discount_available': '20% discount on your next 5 rides',

      // MyCarPage
      'car_documents': 'Car Documents',
      'car_photos': 'Car Photos',
      'car_details': 'Car Details',
      'car_status': 'Car Status',
      'tap_to_add': 'Tap to add',
      'no_car_found': 'No Car Found',
      'add_car_desc': 'Add your car information to get started',
      'noCarFound': 'No car found',

      'logout_confirm': 'Are you sure you want to logout?',
      'retry': 'Retry',

      // General
      'unknown': 'Unknown',
      'id': 'ID',

      // Time & Date
      'time': 'Time',
      'date': 'Date',
      'today': 'Today',
      'yesterday': 'Yesterday',

      // Payment
      'payment': 'Payment',
      'amount': 'Amount',

      // Driver & Passenger
      'passenger_id': 'Passenger ID',

      // Navigation & Actions
      'next': 'Next',
      'view_details': 'View Details',

      // Settings
      'settings': 'Settings',
      'theme': 'Theme',

      // Common Messages
      'success': 'Success',
      'failed': 'Failed',
      'please_wait': 'Please wait...',
      'try_again': 'Try again',
      'connection_error': 'Connection error',
      'server_error': 'Server error',
      'searching_nearby_customers': 'Searching for nearby customers...',

      "no_company_found_login_again": "No company found. Please login again",
      "error_loading_company_info": "Error loading company information",
      "image_too_large": "Image file is too large (max 500KB)",
      "error_selecting_image": "Error selecting image",
      "company_id_required_login_again":
          "Company ID required. Please login again",
      "unknown_error_occurred": "Unknown error occurred",
      "unknown_server_error": "Unknown server error",
      "network_error_occurred": "Network error occurred",
      "image_selected_successfully": "Image selected successfully",
      "user_added_successfully": "User added successfully to",
      "gallery": "Gallery",
      "camera": "Camera",
      "add_photo": "Add Photo",
      "tap_to_select_profile_image": "Tap to select profile image",
      "full_name_required": "Full Name (Required)",
      "enter_full_name": "Enter full name",
      "phone_number_required": "Phone Number (Required)",
      "enter_phone_number": "Enter phone number",
      "email_required": "Email (Required)",
      "enter_email_address": "Enter email address",
      "role_required": "Role (Required)",
      "no_company_selected": "No Company Selected",
      "please_enter_name": "Please enter name",
      "name_must_be_at_least_2_characters":
          "Name must be at least 2 characters",
      "please_enter_phone_number": "Please enter phone number",
      "phone_number_must_be_at_least_8_digits":
          "Phone number must be at least 8 digits",
      "please_enter_email_address": "Please enter email address",
      "please_enter_valid_email_address": "Please enter valid email address",
      "please_select_role": "Please select role",

      "basic_information": "Basic Information",
      "pricing_inventory": "Pricing & Inventory",
      "additional_details": "Additional Details",
      "custom_category": "Custom Category",

      "required_field": "This field is required",
      "invalid_price": "Invalid price",
      "invalid_cost": "Invalid cost",
      "invalid_stock_quantity": "Invalid stock quantity",
      "invalid_minimum_stock": "Invalid minimum stock",
      "product_added_successfully": "Product added successfully",
      "failed_to_add_product": "Failed to add product",
      "product_name_required": "Product name is required",
      "stock_quantity_required": "Stock quantity is required",
      "minimum_stock_required": "Minimum stock is required",
      "unit_price_label": "Unit Price",
      "cost_price_label": "Cost Price",
      "stock_quantity_label": "Stock Quantity",
      "minimum_stock_label": "Minimum Stock",
      "weight_label": "Weight (kg)",
      "dimensions_label": "Dimensions",
      "barcode_label": "Barcode",
      "supplier_id_label": "Supplier ID",
      "product_code_hint": "e.g., PRD-001",
      "sku_hint": "Stock Keeping Unit",
      "dimensions_hint": "L x W x H cm",
      "unit_measure_hint": "piece, kg, liter, etc.",
      "description_hint": "Product description...",
      "notes_hint": "Additional notes about the product...",
      // Authentication & Loading
      'auth_token_not_found':
          'Authentication token not found. Please login again.',
      'session_expired': 'Session expired. Please login again.',
      'failed_to_load_inventory': 'Failed to load inventory',

      // Page Title & Navigation
      'add_stock': 'Add Stock',
      'create_new': 'Create New',
      'add_to_existing': 'Add to Existing',

      // Form Labels - Basic Info
      'product_id': 'Product ID',
      'location_id': 'Location ID',
      'cost_price_lak': 'Cost Price (LAK)',
      'unit_price_lak': 'Unit Price (LAK)',
      'reserved_quantity_optional': 'Reserved Quantity (Optional)',
      'batch_number_optional': 'Batch Number (Optional)',
      'block_location': 'Block Location',
      'expire_date': 'Expire Date',

      // Form Labels - Dropdowns
      'currency': 'Currency',
      'reserved': 'Reserved',

      // Sections & Headers
      'create_new_inventory_item': 'Create New Inventory Item',
      'add_stock_to_existing_item': 'Add Stock to Existing Item',
      'select_inventory_item': 'Select Inventory Item',
      'selected_item_details': 'Selected Item Details',
      'product_location_info': 'Product & Location Information',
      'stock_info': 'Stock Information',
      'pricing_info': 'Pricing Information',
      'additional_info': 'Additional Information',

      // Form Actions & Buttons
      'create_inventory_item': 'Create Inventory Item',
      'quantity_to_add': 'Quantity to Add',
      'reason_for_stock_addition': 'Reason for Stock Addition',
      'add_stock_button': 'Add Stock',
      'clear_form': 'Clear Form',
      'reset': 'Reset',

      // Success Messages
      'inventory_created_success': 'Inventory item created successfully!',
      'stock_added_success': 'Stock added successfully!',
      'form_submitted_success': 'Form submitted successfully!',
      'data_saved_success': 'Data saved successfully!',

      // Error Messages - API
      'failed_to_create_inventory': 'Failed to create inventory',
      'failed_to_add_stock': 'Failed to add stock',
      'error_creating_inventory': 'Error creating inventory',
      'error_adding_stock': 'Error adding stock',
      'api_error': 'API error occurred',

      // Error Messages - Validation
      'fill_all_required_fields': 'Please fill all required fields',
      'enter_valid_number': 'Please enter a valid number',
      'enter_valid_price': 'Please enter a valid price',
      'enter_valid_email': 'Please enter a valid email',
      'enter_valid_phone': 'Please enter a valid phone number',
      'invalid_phone_format': 'Invalid phone format',
      'password_too_short': 'Password is too short',
      'passwords_dont_match': 'Passwords don\'t match',

      // Inventory Related Terms
      'location': 'Location',
      'current_stock': 'Current Stock',
      'available': 'Available',
      'available_quantity': 'Available Quantity',
      'total_stock': 'Total Stock',
      'in_stock': 'In Stock',
      'out_of_stock': 'Out of Stock',
      'inventory': 'Inventory',
      'warehouse': 'Warehouse',
      'supplier': 'Supplier',
      'batch': 'Batch',
      'expiry': 'Expiry',

      // Dropdown Hints & Placeholders
      'select_inventory_item_hint': 'Select an inventory item',
      'select_product': 'Select Product',
      'select_location': 'Select Location',
      'select_supplier': 'Select Supplier',
      'choose_option': 'Choose an option',
      'no_options_available': 'No options available',

      // General UI Text
      'filter': 'Filter',
      'sort': 'Sort',
      'view': 'View',
      'details': 'Details',
      'information': 'Information',
      'profile': 'Profile',

      // Date & Time
      'last_week': 'Last Week',
      'last_month': 'Last Month',
      'date_format': 'MM/dd/yyyy',

      // Confirmation Messages
      'are_you_sure': 'Are you sure?',
      'confirm_logout': 'Are you sure you want to logout?',
      'yes': 'Yes',
      'no': 'No',
      'ok': 'OK',

      // Status Messages
      'processing': 'Processing...',
      'operation_completed': 'Operation completed',
      'operation_failed': 'Operation failed',
      'no_results': 'No results found',

      // Barcode Scanner
      'scan_barcode': 'Scan Barcode',
      'scan_instruction': 'Point your camera at a barcode to scan',
      'camera_permission_denied':
          'Camera permission denied. Please enable camera access in settings.',
      'product_found_success': 'Product found successfully!',
      'product_not_found': 'Product not found with this barcode',
      'failed_to_lookup_product': 'Failed to lookup product',
      'error_looking_up_product': 'Error looking up product',
      'scanned_product': 'Scanned Product',

      // Page Title & Headers
      'add_new_inventory': 'Add New Inventory',

      // Form Fields
      'barcode_required': 'Barcode *',
      'product_id_required': 'Product ID *',

      'cost_price_lak_required': 'Cost Price (LAK) *',
      'unit_price_lak_required': 'Unit Price (LAK) *',

      'store': 'Store',

      // Dropdowns
      'select_store': 'Select store',
      'unknown_location': 'Unknown Location',
      'unknown_store': 'Unknown Store',

      // Buttons
      'creating_inventory': 'Creating...',
      'dismiss': 'Dismiss',
      'confirm_exit': 'Confirm Exit',
      'stay': 'Stay',
      'exit': 'Exit',

      // Scanner
      'initializing_camera': 'Initializing camera...',
      'camera_error': 'Camera error occurred',
      'barcode_detected': 'Barcode detected',

      // Loading States
      'loading_data': 'Loading data...',
      'loading_locations': 'Loading locations...',
      'loading_stores': 'Loading stores...',

      // Error Messages - Validation
      'please_fill_required_fields': 'Please fill all required fields',
      'please_select_location': 'Please select a location',
      'please_select_store': 'Please select a store',
      'please_enter_valid_product_id': 'Please enter a valid Product ID',
      'please_enter_valid_stock_quantity':
          'Please enter a valid Stock Quantity (greater than 0)',
      'please_enter_valid_minimum_stock':
          'Please enter a valid Minimum Stock (0 or greater)',
      'please_enter_valid_cost_price': 'Please enter a valid Cost Price',
      'please_enter_valid_unit_price': 'Please enter a valid Unit Price',
      'location_required': 'Location is required',
      'store_required': 'Store is required',

      // Error Messages - API/Network
      'failed_load_locations': 'Failed to load locations. Please try again.',
      'server_error_locations': 'Server error while loading locations',
      'error_loading_locations':
          'Error loading locations. Check your connection.',
      'failed_load_stores': 'Failed to load stores. Please try again.',
      'server_error_stores': 'Server error while loading stores',
      'error_loading_stores': 'Error loading stores. Check your connection.',

      'product_not_found_message':
          'Product not found. Please check the barcode.',

      'validation_error': 'Validation error. Please check your input.',
      'data_validation_failed':
          'Data validation failed. Please verify your information.',
      'server_error_try_again':
          'Server error occurred. Please try again later.',

      'network_error_check_connection':
          'Network error. Please check your internet connection.',
      'invalid_data_format': 'Invalid data format. Please check your input.',

      // Confirmation Messages
      'creating_inventory_exit_warning':
          'Inventory creation is in progress. Are you sure you want to exit?',

      // App Title
      'deductStock': 'Deduct Stock',
      'deductStockItem': 'Deduct Stock Item',

      // Authentication
      'authTokenNotFound': 'Auth token not found',
      'sessionExpired': 'Session expired',
      'companyIdNotFound': 'Company ID not found',

      // Loading states
      'loadingData': 'Loading data...',
      'loadingLocations': 'Loading locations...',
      'loadingStores': 'Loading stores...',
      'initializingCamera': 'Initializing camera...',
      'deductingStock': 'Deducting stock...',

      // Form fields
      'productId': 'Product ID',
      'productName': 'Product Name',
      'deductAmount': 'Deduct Amount',

      'batchNumber': 'Batch Number (Optional)',
      'supplierId': 'Supplier ID (Optional)',
      'expireDate': 'Expire Date (Optional)',
      'selectExpireDate': 'Select expire date',
      'transactionType': 'Transaction Type',

      // Dropdowns and selections
      'selectLocation': 'Select location',
      'selectStore': 'Select store',
      'locationRequired': 'Location is required',
      'storeRequired': 'Store is required',

      // Buttons
      'scanBarcode': 'Scan Barcode',

      // Messages
      'productFound': 'Product found successfully',
      'productNotFound': 'Product not found',
      'stockDeductedSuccessfully': 'Stock deducted successfully',
      'failedToDeductStock': 'Failed to deduct stock',
      'failedToLoadLocations': 'Failed to load locations',
      'failedToLoadStores': 'Failed to load stores',
      'failedToLookupProduct': 'Failed to lookup product',
      'failedToInitialize': 'Failed to initialize',
      'errorLoadingLocations': 'Error loading locations',
      'errorLoadingStores': 'Error loading stores',
      'errorLookingUpProduct': 'Error looking up product',
      'errorDeductingStock': 'Error deducting stock',
      'networkError': 'Network error - check connection',
      'invalidDataFormat': 'Invalid data format',
      'cameraErrorOccurred': 'Camera error occurred',

      // Validation messages
      'pleaseSelectLocation': 'Please select location',
      'pleaseSelectStore': 'Please select store',
      'pleaseFillRequiredFields': 'Please fill required fields',
      'pleaseEnterValidProductId': 'Please enter a valid product id',
      'pleaseEnterValidAmount': 'Please enter a valid amount',
      'pleaseEnterValidPrice': 'Please enter a valid price',
      'pleaseEnterValidBatchNumber': 'Please enter a valid batch number',
      'pleaseEnterValidSupplierId': 'Please enter a valid supplier id',
      'fieldIsRequired': 'Field is required',
      'enterValidNumber': 'Enter a valid number',
      'enterValidPrice': 'Enter a valid price',

      // Scanner
      'scannedProduct': 'Scanned Product',
      'barcodeDetected': 'Barcode detected',
      'positionBarcodeWithinFrame': 'Position barcode within the frame to scan',

      // Confirmation dialogs
      'confirmExit': 'Confirm Exit',
      'confirmExitMessage':
          'Are you sure you want to exit while deducting stock?',

      // Misc
      'na': 'N/A',
      'unknownStore': 'Unknown Store',
      'expiry_dashboard': 'Expiry Dashboard',
      'inventory_summary': 'Inventory Summary',
      'total_items': 'Total Items',
      'good': 'Good',
      'expiring': 'Expiring',
      'no_expiry': 'No Expiry',
      'good_status': 'Good Status',
      'expiring_soon_status': 'Expiring Soon Status',
      'expired_status': 'Expired Status',
      'no_expiry_status': 'No Expiry Status',
      'loading_expiry_data': 'Loading expiry data...',
      'no_expiry_items_found': 'No expiry items found',
      'showing_items': 'Showing',
      'items': 'Items',
      'show_all_items': 'Show All Items',
      'quantity': 'Quantity',
      'expires': 'Expires',
      'never_expires': 'Never expires',
      'no_expiry_date': 'No expiry date',
      'manage_expiry': 'Manage Expiry',
      'manage_item': 'Manage Item',
      'unknown_product': 'Unknown Product',
      'qty': 'Qty',
      'branch': 'Branch',
      'vendor': 'Vendor',
      'select_vendor': 'Select Vendor',
      'add_vendor': 'Add Vendor',
      'edit_vendor': 'Edit Vendor',
      'delete_vendor': 'Delete Vendor',
      'vendor_name': 'Vendor Name',
      'contact_person': 'Contact Person',
      'phone_number': 'Phone Number',
      'email_address': 'Email Address',
      'address': 'Address',
      'vendor_added_successfully': 'Vendor added successfully',
      'vendor_updated_successfully': 'Vendor updated successfully',
      'vendor_deleted_successfully': 'Vendor deleted successfully',
      'delete_vendor_confirmation':
          'Are you sure you want to delete this vendor?',
      'no_vendors_found': 'No vendors found',
      'search_vendors_hint':
          'Search vendors by name, contact person, or phone...',
      'dashboard': 'Dashboard',
      'deduct': 'Deduct',
      'increase': 'Add Stock',
      'logout_confirmation': 'Are you sure you want to logout?',
      'select_theme': 'Select Theme',
      'settings_management': 'Settings & Management',
      // English translations for DeductStockPage
      'deduct_stock': 'Deduct Stock',
      'increase_stock': 'Increase Stock',
      'deduct_stock_item': 'Deduct Stock Item',
      'deduct_amount': 'Deduct Amount',
      'batch_number': 'Batch Number',
      'optional': 'Optional',
      'select_expire_date': 'Select Expire Date',
      'deduct_stock_confirmation': 'Confirm Stock Deduction',
      'deduct_stock_confirmation_message':
          'Are you sure you want to deduct this stock?',
      'stock_deducted_successfully': 'Stock deducted successfully',
      'failed_to_deduct_stock': 'Failed to deduct stock',
      'deducting_stock': 'Deducting stock...',
      'group': 'Group',
      'merchants': 'Merchants',
      'terminal': 'Terminal',
      'Terminal': 'Terminal',
      'home_menu': 'Dashboard',
      'error_save_theme': 'Error saving theme',
      'error_save_language': 'Error saving language',
      'welcome_inventory': 'Welcome to Inventory Management',
      'inventory_description': 'inventory description',
      'coming_soon': 'coming soon',
      'select_language': 'Select Language',

      // --- Vendor Management (NEW) ---
      'vendors': 'Vendors',
      'update_vendor': 'Update Vendor',

      'vendor_code': 'Vendor Code',
      'manager_name': 'Manager Name',
      'vendor_image': 'Vendor Image',
      'tap_to_change_image': 'Tap to change image',
      'image_updates_not_supported':
          'Image updates are not currently supported by the API',
      'vendor_information': 'Vendor Information',
      'no_vendor_selected': 'No Vendor Selected',
      'image_updated_successfully': 'Image updated successfully',
      'select_image_source': 'Select Image Source',

      'image_update': 'Image Update',
      'image_update_info':
          'Image updates are not currently supported by the API. You can view the current image but cannot change it through this interface.',
      'tap_for_more_information': 'Tap for more information',

      'add_location': 'Add Location',
      'edit_location': 'Edit Location',
      'delete_location': 'Delete Location',
      'update_location': 'Update Location',
      'no_locations_found': 'No locations found',
      'location_name': 'Location Name',
      'location_code': 'Location Code',
      'location_added_successfully': 'Location added successfully',
      'location_updated_successfully': 'Location updated successfully',
      'location_deleted_successfully': 'Location deleted successfully',
      'delete_location_confirmation':
          'Are you sure you want to delete this location?',
      'search_locations_hint': 'Search locations by name or description...',

      // --- Group Management (NEW) ---
      'groups': 'Groups',
      'add_group': 'Add Group',
      'edit_group': 'Edit Group',
      'delete_group': 'Delete Group',
      'update_group': 'Update Group',
      'no_groups_found': 'No groups found',
      'group_name': 'Group Name',
      'group_code': 'Group Code',
      'group_added_successfully': 'Group added successfully',
      'group_updated_successfully': 'Group updated successfully',
      'group_deleted_successfully': 'Group deleted successfully',
      'delete_group_confirmation':
          'Are you sure you want to delete this group?',
      'search_groups_hint': 'Search groups by name or code...',
      "enter_barcode": "Enter Barcode",
      "enter_product_barcode": "Enter product barcode",
      "add_stock_item": "Add Stock Item",
      "adding_stock": "Adding stock...",
      "error_loading_vendors": "Error loading vendors",
      "Refresh": "Refresh",
      'deduct_stock_button': 'Deduct Stock',
      "Location": "Location",
      "Select ": "Select ",
      'lao_kip': 'Lao Kip',
      'thai_baht': 'Thai Baht',
      'us_dollar': 'US Dollar',
      'position_barcode_instruction':
          'Position the barcode within the scanning area',
      'select_product_to_deduct': 'Select Product to Deduct',
      'failed_to_initialize': 'Failed to initialize',
      'empty_response_from_server': 'Empty response from server',
      'error_loading_products': 'Error loading products',
      'failed_to_load_locations': 'Failed to load locations',
      'selected': 'Selected',
      'product_found_successfully': 'Product found successfully',
      'error_deducting_stock': 'Error deducting stock',
      'this_field_is_required': 'This field is required',
      'loading_products': 'Loading products...',
      'supplier_id_optional': 'Supplier ID (Optional)',
      'expire_date_optional': 'Expire Date (Optional)',
      'choose_location': 'Choose a location',
      'choose_store': 'Choose a store',
      'select_a_product': 'Select a product',
      'no_products_available': 'No products available',
      'no_locations_available': 'No locations available',
      'no_stores_available': 'No stores available',
      'load_products': 'Load Products',
      'load_locations': 'Load Locations',
      'load_stores': 'Load Stores',
      'products_available': 'products available',
      'locations_available': 'locations available',
      'stores_available': 'stores available',
      'error_logout': 'Error during logout',
      'manage_system_settings': 'Configure and manage all system',
      'company': 'Company',
      'merchant': 'Merchant',
      'help': 'Help',
      'language_changed': 'Language changed to',
      'theme_changed': 'Theme changed to',
      // Error messages
      'failed_to_load_groups': 'Failed to load groups',
      'failed_to_load_merchants': 'Failed to load merchants',
      'failed_to_load_stores': 'Failed to load stores',
      'failed_to_load_terminals': 'Failed to load terminals',
      'please_select_at_least_one_terminal':
          'Please select at least one terminal',
      'terminal_already_exists': 'Terminal already exists',
      'failed_to_process_terminals': 'Failed to process terminals',

      // Page title and headers
      'terminal_management': 'Terminal Management',
      'terminal_selection': 'Terminal Selection',
      'filters': 'Filters',
      'terminals': 'Terminals',

      // Form labels and hints
      'select_group': 'Select group',
      'select_merchant': 'Select merchant',
      'select_a_group_optional': 'Select a group (optional)',
      'select_a_merchant_optional': 'Select a merchant (optional)',
      'select_a_store_optional': 'Select a store (optional)',
      'loading_groups': 'Loading groups...',
      'loading_merchants': 'Loading merchants...',
      'loading_terminals': 'Loading terminals...',
      'select_group_first': 'Select group first',
      'select_merchant_first': 'Select merchant first',

      // Terminal selection
      'select_terminals': 'Select Terminals',
      'select_all': 'Select All',
      'clear': 'Clear',
      'select_a_store_to_view_terminals': 'Select a store to view terminals',
      'no_terminals_found': 'No terminals found',
      'terminals_selected': 'terminals selected',

      // Table headers
      'terminal_name': 'Terminal Name',
      'code': 'Code',
      'terminal_id': 'Terminal ID',
      'company_id': 'Company ID',
      'store_id': 'Store ID',
      'has_image': 'Has Image',
      'n_a': 'N/A',

      // Action buttons
      'process_selected': 'Process Selected',

      // Status and info
      'company_id_label': 'Company ID',
      'code_label': 'Code',
      'of': 'of',
      'Company': 'Info',
      // Messages
      'failed_to_generate_pdf': 'Failed to generate PDF',
      'failed_to_generate_excel': 'Failed to generate Excel',
      'excel_file_downloaded_successfully':
          'Excel file downloaded successfully',

      // Status labels
      'expiring_soon': 'Expiring Soon',
      'valid': 'Valid',
      'no_code': 'No Code',

      // Header content
      'terminal_registration_complete': 'Terminal Registration Complete',
      'registration_completed_successfully':
          'Registration completed successfully',
      'registered_terminals': 'Registered terminals',

      // Button labels
      'generating': 'Generating...',
      'pdf_report': 'PDF Report',
      'excel_export': 'Excel Export',

      // PDF Report content
      'terminal_registration_form_report': 'TERMINAL REGISTRATION FORM REPORT',
      'generated': 'Generated',
      'organization_hierarchy_summary': 'Organization Hierarchy Summary',
      'group_information': 'Group Information',
      'merchant_information': 'Merchant Information',
      'store_information': 'Store Information',
      'mobile': 'Mobile',
      'manager': 'Manager',
      'upi_percentage': 'UPI %',
      'visa_percentage': 'Visa %',
      'master_percentage': 'Master %',

      // Table headers
      'serial_number': 'Serial Number',
      'sim_number': 'SIM Number',
      'total_terminals_registered': 'Total Terminals Registered',
      'report_generated': 'Report Generated',

      // Signature section
      'approved_by': 'APPROVED BY',
      'created_by': 'CREATED BY',
      'signature': 'Signature',
      'signatures': 'Signatures',
      'store_manager': 'Store Manager',
      'store_email': 'Store Email',

      // Terminal details
      'path': 'Path',
      'serial': 'Serial',
      'sim': 'SIM',

      // Page title
      'register_form_for_terminal': 'Register Form for Terminal',
      "auth_error": "Authentication failed. Please login again.",
      "load_error": "Failed to load data",
      "fetch_error": "Failed to fetch data",
      "unknown_error": "Unknown error occurred",
      "http_error": "Network error",
      "unknown_status": "Unknown status",
      "select": "Select",
      "showing": "Showing",

      "location_dashboard": "Location Dashboard",
      "loading_location_data": "Loading location data...",
      "location_summary": "Location Summary",
      "total_locations": "Total Locations",
      "good_stock": "Good Stock",
      "warning_stock": "Warning Stock",
      "critical_stock": "Critical Stock",
      "no_location_items_found": "No location items found",
      "stock_status": "Stock Status",
      "total_value": "Total Value",
      "record_count": "Record Count",
      "manage_location": "Manage Location",
      "search_products": "Search products...",
      "clear_filters": "Clear Filters",
      "products_summary": "Products Summary",
      "no_products_match_filters": "No products match your filters",
      "total_amount": "Total Amount",
      "product_information": "Product Information",
      "view_inventory": "View Inventory",
};